channels:
 - defaults
 - conda-forge
 - alubbock
dependencies:
 - biopython
 - matplotlib
 - numpy
 - scipy
 - scikit-learn
 - scikit-image
 - seaborn
 - pandas
 - pysb
 - opencv
 - pip:
   - imutils
   - prody
